''

diff --git a/bin/mailsync b/bin/mailsync
--- a/bin/mailsync
+++ b/bin/mailsync
@@ -1,14 +1,44 @@
 #!/bin/bash
+#
+# 
 
-# Run only if user logged in (prevent cron errors)
-pgrep -u "${USER:=$LOGNAME}" >/dev/null || { echo "$USER not logged in; sync will not run."; exit ;}
+#TODO: docs + make similar one for vdirsyncer
 
-# Run only if not already running in other instance
-pgrep -x mbsync >/dev/null && { echo "mbsync is already running." ; exit ;}
+sync(){
+    check
+    start_davmail
+    start_mbsyncer
+    kill_davmail
+    echo 'Email sync done.'
+}
 
-# Checks for internet connection and set notification script.
-ping -q -c 1 1.1.1.1 > /dev/null || { echo "No internet connection detected."; exit ;}
+check() {
+    # Run only if user logged in (prevents systemd errors)
+    pgrep -u "${USER:=$LOGNAME}" >/dev/null || { echo "$USER not logged in; sync will not run."; exit ;}
 
-mbsync -a -q || { echo 'Email sync failed.'; exit ;}
+    # Checks for internet connection and set notification script.
+    ping -q -c 1 1.1.1.1 > /dev/null || { echo "No internet connection detected."; exit ;}
+}
 
-echo 'Email sync done.'
+start_davmail() {
+    pgrep -f davmail >/dev/null || davmail $HOME/.config/davmail/davmail.properties &
+    sleep 2
+}
+
+start_mbsyncer() {
+    pgrep -x mbsync >/dev/null && { echo "mbsync is already running." ; kill_davmail; exit ;}
+    mbsync -a -q -q || { echo 'Email sync failed.'; kill_davmail; exit ;}
+}
+
+kill_davmail() {
+    kill $(pgrep -f davmail)
+}
+
+start_message='Email sync started'
+if [[ -z $TMUX ]]; then
+    echo "$start_message"
+    sync 
+else
+    tmux display -d 1000 "$start_message"
+    tmux display -d 2000 "$(sync)"
+fi
