'Automatic Update'

diff --git a/dotfiles-linux/tmux/tmux-fzf-url/regex-extra b/dotfiles-linux/tmux/tmux-fzf-url/regex-extra
--- a/dotfiles-linux/tmux/tmux-fzf-url/regex-extra
+++ b/dotfiles-linux/tmux/tmux-fzf-url/regex-extra
@@ -1,3 +1,6 @@
+#!/usr/bin/env bash
+set -euo pipefail
+
 # This script is used to grep the follow text from stdin:
 
 # |--------------+----------------------------+-----------------------------------+----------------------|
@@ -13,9 +16,12 @@
 
 # - {file}:{line}:{column}
 
-RE_URL='(https?|ftp|file):/?//[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'
-RE_WWW='(http://|https://)?www\.[a-zA-Z](-?[a-zA-Z0-9])+\.[a-zA-Z]{2,}(/\S+)*'
-RE_IP='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(:[0-9]{1,5})?(/\S+)*'
 RE_PYTEST_ERROR="^[a-zA-Z0-9\\\/\_\.\-]*\.py:[0-9]+:"
 RE_PYTHON_ERROR="\"([a-zA-Z0-9\\\/\_\.]*\.py)\",\sline\s([0-9]+)"
 RE_CLANG_ERROR=""
+
+################################################################################
+# Combine the regexes into 1. All patterns that match will also be send to fzf
+# for selection.
+################################################################################
+echo "($RE_PYTEST_ERROR)|($RE_CLANG_ERROR)|($RE_PYTHON_ERROR)"
