'Automatic Update'

diff --git a/dotfiles-linux/bin/calsync b/dotfiles-linux/bin/calsync
--- a/dotfiles-linux/bin/calsync
+++ b/dotfiles-linux/bin/calsync
@@ -20,20 +20,42 @@ error=/dev/stderr
 output=/dev/stdout
 options=$(getopt -o qh --long quiet,help -- "$@")
 
-[ $? -eq 0 ] || { echo "Incorrect options provided"; exit 1; }
+[ $? -eq 0 ] || {
+    echo "Incorrect options provided"
+    exit 1
+}
 
 eval set -- "$options"
 while true; do
     case "$1" in
-        -q|--quiet) output=/dev/null; error=/dev/null; shift ;;
-        -h|--help) echo "$usage"; exit ;;
-        --) shift; break ;;
-        *) echo "Internal error"; exit 1 ;;
+    -q | --quiet)
+        output=/dev/null
+        error=/dev/null
+        shift
+        ;;
+    -h | --help)
+        echo "$usage"
+        exit
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "Internal error"
+        exit 1
+        ;;
     esac
 done
 
-[ $# -eq 0 ] && { echo "$usage"; exit ;}
-[ $# -lt 5 ] && { echo "Missing positional arguments"; exit ;}
+[ $# -eq 0 ] && {
+    echo "$usage"
+    exit
+}
+[ $# -lt 5 ] && {
+    echo "Missing positional arguments"
+    exit
+}
 
 davmailconfig=$1
 orgfile=$2
@@ -45,12 +67,26 @@ khalorg=$@
 # logged in, if there is an internet connection, starts davmail, runs the
 # synchronization and kills davmail afterwards.
 ##############################################################################
-main(){
-    is_logged_in || { echo "$USER not logged in; sync will not run."; exit ;}
-    has_internet || { echo "No internet connection detected."; exit ;}
+main() {
+    is_logged_in || {
+        echo "$USER not logged in; sync will not run."
+        exit
+    }
+    has_internet || {
+        echo "No internet connection detected."
+        exit
+    }
     start_davmail
-    vdirsyncer -v CRITICAL sync || { echo "vdirsyncer failed"; kill_davmail; exit ; }
-    khalorg_list || { echo "khalorg failed"; kill_davmail; exit; }
+    vdirsyncer -v CRITICAL sync || {
+        echo "vdirsyncer failed"
+        kill_davmail
+        exit
+    }
+    khalorg_list || {
+        echo "khalorg failed"
+        kill_davmail
+        exit
+    }
     kill_davmail
     echo 'Calendar sync done.'
 }
@@ -60,7 +96,7 @@ main(){
 # user has a process with the same name as the user id.
 ##############################################################################
 is_logged_in() {
-    pgrep -u "${USER:=$LOGNAME}" 1> $output 2> $error
+    pgrep -u "${USER:=$LOGNAME}" 1>$output 2>$error
 }
 
 ##############################################################################
@@ -68,7 +104,7 @@ is_logged_in() {
 # pinging a known ip address.
 ##############################################################################
 has_internet() {
-    ping -q -c 1 1.1.1.1 1> $output 2> $error
+    ping -q -c 1 1.1.1.1 1>$output 2>$error
 }
 
 ##############################################################################
@@ -76,8 +112,8 @@ has_internet() {
 # checking if there is a process with the name 'davmail.jar'.
 ##############################################################################
 start_davmail() {
-    pgrep -f davmail\.jar 1> $output 2> $error && return
-    davmail $davmailconfig 1> $output 2> $error &
+    pgrep -f davmail\.jar 1>$output 2>$error && return
+    davmail $davmailconfig 1>$output 2>$error &
     pid_davmail=$!
     sleep 0.5
 }
@@ -94,18 +130,26 @@ kill_davmail() {
 # This function runs khalorg list.
 ##############################################################################
 khalorg_list() {
-    khalorg list $khalorg > $orgfile
+    khalorg list $khalorg >$orgfile
+}
+
+#############################################################################
+# This function is used to display a message in a tmux session. The message can
+# be provided as an argument, or through stdin. If tmux is not running, the
+# message will be printed to stderr.
+##############################################################################
+tmux_display() {
+    msg=${1:-$(cat)}
+    if [[ $TMUX ]]; then
+        tmux display -p -d 2000 "$msg" >&2
+    else
+        echo "$msg" >&2
+    fi
 }
 
 ##############################################################################
 # Execute the main function. If the script is run in a tmux session, the output
 # will be displayed in a tmux message.
 ##############################################################################
-start_message='Calendar sync started'
-if [[ $TMUX ]]; then
-    tmux display -d 1000 "$start_message"
-    tmux display -d 2000 "$(main)"
-else
-    echo "$start_message"
-    main
-fi
+tmux_display "Calendar sync started"
+main | tmux_display
