''

diff --git a/dotfiles-linux/bin/mailsync b/dotfiles-linux/bin/mailsync
--- a/dotfiles-linux/bin/mailsync
+++ b/dotfiles-linux/bin/mailsync
@@ -2,7 +2,9 @@
 
 usage="Usage: $(basename "$0") [-h | --help] <davmail-config> 
 
-Sychronize all \`mbsyncer\` channels and index them with \`notmuch\` using an imap connection with \`davmail\`.
+Sychronize all \`mbsyncer\` channels and index them with \`notmuch\` using an
+imap connection with \`davmail\`. If no davmail config is provided, ignore
+davmail, and only run \`mbsyncer\` and \`notmuch\`.
 
 where:
     options
@@ -16,29 +18,50 @@ error=/dev/stderr
 output=/dev/stdout
 options=$(getopt -o qh --long quiet,help -- "$@")
 
-[ $? -eq 0 ] || { echo "Incorrect options provided"; exit 1; }
+[ $? -eq 0 ] || {
+    echo "Incorrect options provided"
+    exit 1
+}
 
 eval set -- "$options"
 while true; do
     case "$1" in
-        -q|--quiet) output=/dev/null; error=/dev/null; shift ;;
-        -h|--help) echo "$usage"; exit ;;
-        --) shift; break ;;
-        *) echo "Internal error"; exit 1 ;;
+        -q | --quiet)
+            output=/dev/null
+            error=/dev/null
+            shift
+            ;;
+        -h | --help)
+            echo "$usage"
+            exit
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Internal error"
+            exit 1
+            ;;
     esac
 done
 
-[ $# -eq 0 ] && { echo "$usage"; exit ;}
-davmailconfig="$1"
+[[ $1 ]] && davmailconfig=$1
 
 ##############################################################################
 # This function is the main function of the script. It checks if the user is
-# logged in, if there is an internet connection, starts davmail, runs the 
+# logged in, if there is an internet connection, starts davmail, runs the
 # synchronization and kills davmail afterwards.
 ##############################################################################
-main(){
-    is_logged_in || { echo "$USER not logged in; sync will not run."; exit ;}
-    has_internet || { echo "No internet connection detected."; exit ;}    
+main() {
+    is_logged_in || {
+        echo "$USER not logged in; sync will not run."
+        exit
+    }
+    has_internet || {
+        echo "No internet connection detected."
+        exit
+    }
     start_davmail
     start_mbsyncer
     start_notmuch
@@ -51,7 +74,7 @@ main(){
 # user has a process with the same name as the user id.
 ##############################################################################
 is_logged_in() {
-    pgrep -u "${USER:=$LOGNAME}" 1> $output 2> $error
+    pgrep -u "${USER:=$LOGNAME}" 1>$output 2>$error
 }
 
 ##############################################################################
@@ -59,7 +82,7 @@ is_logged_in() {
 # pinging a known ip address.
 ##############################################################################
 has_internet() {
-    ping -q -c 1 1.1.1.1 1> $output 2> $error
+    ping -q -c 1 1.1.1.1 1>$output 2>$error
 }
 
 ##############################################################################
@@ -67,8 +90,9 @@ has_internet() {
 # checking if there is a process with the name 'davmail.jar'.
 ##############################################################################
 start_davmail() {
-    pgrep -f davmail\.jar 1> $output 2> $error && return
-    davmail $davmailconfig 1> $output 2> $error &
+    [[ $davmailconfig ]] || return
+    pgrep -f davmail\.jar 1>$output 2>$error && return
+    davmail $davmailconfig 1>$output 2>$error &
     pid_davmail=$!
     sleep 1
 }
@@ -78,8 +102,16 @@ start_davmail() {
 # checking if there is a process with the name 'mbsync'.
 ##############################################################################
 start_mbsyncer() {
-    pgrep -x mbsync 1> $output 2> $error && { echo "mbsync is already running." ; kill_davmail; exit ;}
-    mbsync -a -q -q 1> $output 2> $error|| { echo 'Email sync failed.'; kill_davmail; exit ;}
+    pgrep -x mbsync 1>$output 2>$error && {
+        echo "mbsync is already running."
+        kill_davmail
+        exit
+    }
+    mbsync -a -q -q 1>$output 2>$error || {
+        echo 'Email sync failed.'
+        kill_davmail
+        exit
+    }
 }
 
 ##############################################################################
@@ -87,8 +119,16 @@ start_mbsyncer() {
 # checking if there is a process with the name 'notmuch'.
 ##############################################################################
 start_notmuch() {
-    pgrep -x notmuch 1> $output 2> $error && { echo "notmuch is already running." ; kill_davmail; exit ;}
-    notmuch new --quiet 1> $output 2> $error || { echo 'Email sync failed.'; kill_davmail; exit ;}
+    pgrep -x notmuch 1>$output 2>$error && {
+        echo "notmuch is already running."
+        kill_davmail
+        exit
+    }
+    notmuch new --quiet 1>$output 2>$error || {
+        echo 'Email sync failed.'
+        kill_davmail
+        exit
+    }
 }
 
 ##############################################################################
@@ -96,6 +136,7 @@ start_notmuch() {
 # is a process with the name 'davmail.jar'.
 ##############################################################################
 kill_davmail() {
+    [[ $davmailconfig ]] || return
     [[ $pid_davmail ]] && kill $pid_davmail
 }
 
@@ -111,6 +152,5 @@ if [[ $TMUX ]]; then
     tmux display -d 2000 "$(main)"
 else
     echo "$start_message"
-    main 
+    main
 fi
-
